name: Accessibility
on:
  pull_request:
    types: opened
  issues:
    types: opened
  issue_comment:
    types: created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GeopJr/action-accessibility@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

